services:
  web:
    build: .
    container_name: saint-codes-web
    environment:
      - NODE_ENV=development
    ports:
      - "4321:4321"
    volumes:
      # mount local source into container
      - "./:/app"
      # paths below are ephemeral volumes
      - "/app/.tscache"
      - "/app/dist"
      - "/app/node_modules"
