[build]
  command = 'npm run deploy:prod'
  publish = 'public'
  functions = 'netlify/functions'

[dev]
  command = 'npm run deploy:dev'
  publish = 'public'
  port = 3000

[[redirects]]
from = 'projects/particles/*'
to = 'https://saint-codes-particles.netlify.app/code/:splat'
status = 200

[[redirects]]
from = 'projects/particle-orb/*'
to = 'https://saint-codes-particles.netlify.app/code/:splat'
status = 200

[[redirects]]
from = 'projects/broken-clocks/*'
to = 'https://saint-codes-particles.netlify.app/code/:splat'
status = 200
